apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-gateway
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kong-gateway
    app.kubernetes.io/part-of: medikong-platform
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kong
  selector:
    matchLabels:
      enable-metrics: "true"
      app.kubernetes.io/instance: kong
      app.kubernetes.io/name: kong
  endpoints:
    - targetPort: status
      path: /metrics
      interval: 30s
    - targetPort: cmetrics
      path: /metrics
      interval: 30s
