environment: dev

nodeSelector: null

image:
  registry: localhost:5001
  tag: dev
  pullPolicy: Always

deployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1

container:
  readinessProbe:
    initialDelaySeconds: 1
    periodSeconds: 2
  resources:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 384Mi

observability:
  tracing:
    enabled: true
    otlpEndpoint: http://opentelemetry-collector.observability.svc.cluster.local:4317
    excludedUrls: /health,/healthz,/readyz,/metrics
  profiling:
    enabled: true
    serverAddress: http://pyroscope.observability.svc.cluster.local:4040
    sampleRate: 100
    spanProfilesEnabled: true

pdb:
  enabled: false

hpa:
  enabled: false

serviceMonitor:
  enabled: true
