alloy:
  enabled: false

agent:
  enabled: false

minio:
  enabled: false

pyroscope:
  replicaCount: 1
  disableSelfProfile: true
  image:
    registry: docker.io
    repository: grafana/pyroscope
    tag: 2.0.3
  extraArgs:
    log.level: info
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 768Mi

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
  interval: 30s
