env:
  database: "off"

deployment:
  daemonset: false

admin:
  enabled: false

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

proxy:
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  tls:
    enabled: false

ingressController:
  enabled: true
  ingressClass: kong
  createIngressClass: true

postgresql:
  enabled: false
