environment: aws-scenario

image:
  registry: 941141115079.dkr.ecr.ap-northeast-2.amazonaws.com
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-registry

deployment:
  replicas: 1
  podLabels:
    medikong.io/scenario: "true"

container:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

pdb:
  enabled: false

hpa:
  enabled: false

serviceMonitor:
  enabled: false
