deploymentMode: SingleBinary

chunksCache:
  enabled: false

resultsCache:
  enabled: false

loki:
  auth_enabled: false
  image:
    repository: grafana/loki
    tag: 3.6.7
  commonConfig:
    replication_factor: 1
  limits_config:
    retention_period: 24h
  compactor:
    compaction_interval: 10m
    retention_enabled: true
    delete_request_store: filesystem
    working_directory: /var/loki/compactor
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: filesystem

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

gateway:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
